/*
Task 1 - easy - 2xp

Create a variable called `myName` and assign it the value of your name. Output the variable to the console.

Requirements:
- Variable must be of type 'String'
- Variable must have a value
- Variable myname printed to console
*/

// My solution:
// write your code here
String myName = 'John Doe';
System.debug(myName);

// Learn-Apex (LA) solution:
/*
String myName = 'John Doe'; System.debug(myName);
*/
