public class VariableOperationsTasks {

  /*
  TASK 1
  Create two integer variables `a` and `b` with values 15 and 22 respectively. Then, create a third integer variable `sum` that stores the sum of `a` and `b`. Output `a`, `b`, and `sum`.
  */
  public static void task1() {
    // write your code here
    Integer a = 15;
    Integer b = 22;
    Integer sum = a + b;
    System.debug(a);
    System.debug(b);
    System.debug(sum);
  }


  /*
  TASK 2
  Create two integer variables `varOne` and `varTwo` with values any value you want. Then, create a third integer variable `sum` that stores the sum of `varOne` and `varTwo`. Output `varOne, `varTwo` and `sum` to the console.
  */
  public static void task2() {
    // write your code here
    Integer varOne = 1;
    Integer varTwo = 2;
    Integer sum = varOne + varTwo;
    System.debug(varOne);
    System.debug(varTwo);
    System.debug(sum);
  }


  /*
  TASK 3
  Create two integer variables `var1` and `var2` with any values you want. Then, create a third integer variable `diff` that stores the difference between `var2` and `var1`.
  */
  public static void task3() {
    Integer var1 = 10;
    Integer var2 = 20;
    Integer diff = var2 - var1;

    System.debug(var1);
    System.debug(var2);
    System.debug(diff);
  }


  /*
  TASK 4
  Create two integer variables `multiplier` and `multiplicand` with any values you want. Then, create a third integer variable `product` that stores the product of `multiplier` and `multiplicand`.
  */
  public static void task4() {
    Integer multiplier = 10;
    Integer multiplicand = 20;
    Integer product = multiplicand * multiplier;

    System.debug(multiplier);
    System.debug(multiplicand);
    System.debug(product);
  }

}
