public class VariableTypesTasks {

  /*
  TASK 1
  Create a variable called `name` and assign it the value 'Alex'. Output the variable to the console.
  */
  public static void task1() {
    String name = 'Alex';
    System.debug(name);
  }


  /*
  TASK 2
  Create a variable called `email` and assign it the value 'alex@mail.com'.
  */
  public static void task2() {
    String email = 'alex@mail.com';
    System.debug(email);
  }


  /*
  TASK 3
  Create a variable called `abc` and assign it the value 123.
  */
  public static void task3() {
    Integer abc = 123;
    System.debug(abc);
  }


  /*
  TASK 4
  Create a variable called `half` and assign it the value 0.5.
  */
  public static void task4() {
    Decimal half = 0.5;
    System.debug(half);
  }


  /*
  TASK 5
  Create a variable called `trueVariable` and assign it the value true.
  */
  public static void task5() {
    Boolean trueVariable = true;
    System.debug(trueVariable);
  }


  /*
  TASK 6
  Create a variable called `falseValue` and assign it the value false.
  */
  public static void task6() {
    Boolean falseValue = false;
    System.debug(falseValue);
  }
}