public class VariablesBasicsTasks {

  /*
  TASK 1
  Create a variable called `myName` and assign it the value of your name. Output the variable to the console.
  */
  public static void task1() {  
    // write your code here
    String myName = 'John Doe';
    System.debug(myName);
  }


  /*
  TASK 2
  Create a variable called 'myAge' and assign it the value of your age. Output the variable to the console.
  */
  public static void task2() {
    // write your code here
    Integer myAge = 60;
    System.debug(myAge);
  }


  /*
  TASK 3
  Create an integer variable called 'answerForEverything' and assign it the value 42. Print it out to console.
  */
  public static void task3() {
    Integer answerForEverything = 42;
    System.debug(answerForEverything);
  }


  /*
  Create a string variable called 'book' and assign it the value 'Harry Potter'. Print it out to the console.
  */
  public static void task4() {
    String book = 'Harry Potter';
    System.debug(book);
  }  

}
